using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SWAT.Applications.Claw
{
    public static class KeywordConstants
    {
        public const string STEPNOTEXECUTED = "STEPNOTEXECUTED";
        public const string TESTCASE_START = "TESTCASE.START";
        public const string TESTCASE_STOP = "TESTCASE.STOP";

        public const string SERVICE_COPYROW = "SERVICE.COPYROW";
        public const string SERVICE_COPYCOLUMN = "SERVICE.COPYCOLUMN";
        public const string SERVICE_IMPORTEXCEL = "SERVICE.IMPORTEXCEL";
        public const string SERVICE_OPENBROWSER = "SERVICE.OPENBROWSER";
        //CLAW
        public const string CLAW_OPEN = "CLAW.OPEN";
        public const string CLAW_LOGOUT = "CLAW.LOGOUT";
        public const string CLAW_LOGIN = "CLAW.LOGIN";
        public const string CLAW_NAVIGATETO = "CLAW.NAVIGATETO";
        //DashBoard
        public const string DASHBOARD_GADGETS_VERIFY = "CLAW.GADGETS.VERIFY";
        public const string DASHBOARD_REPORT_OPEN = "CLAW.DASHBOARD.DASHBOARDOPEN";
        //ROUTINGGUIDE
        public const string ROUTINGGUIDE_VERIFY_LANE = "CLAW.ROUTINGGUIDE.VERIFY.LANE";
        public const string ROUTINGGUIDE_ADVSEARCH = "CLAW.ROUTINGGUIDE_ADVSEARCH";
        public const string ROUTINGGUIDE_NAVIGATE = "CLAW.ROUTINGGUIDE.NAVIGATE";
        public const string ROUTINGGUIDE_CUSTOMER_SEARCH = "CLAW.ROUTINGGUIDE_CUSTOMER_SEARCH";
        public const string ROUTINGGUIDE_ADDVERFIY = "CLAW.ROUTINGGUIDE.ADDVERIFY";
        public const string ROUTINGGUIDE_ADDLANEVERFIY = "CLAW.ROUTINGGUIDE.ADDLANEVERFIY";

        //CALCULATEDISTANCE
        public const string CALCULATEDISTANCE = "CLAW.CALCULATEDISTANCE";
        //ACCOUNTING
        public const string ACCOUNTING_ACCFILTER = "CLAW.ACCOUNTING.ACCFILTER";
        public const string ACCOUNTING_ACCSORT = "CLAW.ACCOUNTING.ACCSORT";
        public const string ACCOUNTING_OPENLOAD = "CLAW.ACCOUNTING.OPENLOAD";
        //USER
        public const string USER_SERACH = "CLAW.USER.SERACH";
        public const string USER_NAVIGATETOALLPAGE = "CLAW.USER.NAVIGATETOALLPAGE";
        public const string USER_EMULATE = "CLAW.USER.EMULATE";
        public const string USER_SEARCHANDOPEN = "CLAW.USER.SEARCHANDOPEN";
        public const string USER_VERIFY = "CLAW.USER_VERIFY";
        public const string USER_CHANGEPASSWORD = "CLAW.USER.CHANGEPASSWORD";
        public const string USER_GENERALINFO = "CLAW.USER.GENERALINFO";
        public const string USER_PROFILE = "CLAW.USER.PROFILE";
        //FACILITY
       
        public const string FACLITY_SEARCHANDOPEN = "CLAW.FACLITY.SEARCHANDOPEN";
        public const string FACLITY_VERIFYINFO = "CLAW.FACLITY.VERIFYINFO";
        
        //CUSTOMER
        public const string CUSTOMER_SEARCHANDOPEN = "CLAW.CUSTOMER.SEARCHANDOPEN";
        public const string CUSTOMER_VERIFYDETAILS = "CLAW.CUSTOMER.VERIFYDETAILS";
        public const string CUTOMER_APPACCESS = "CLAW.CUSTOMER.APPACCESS";
        public const string CUSTOMER_MANAGECUSTOMERS_MYLOADSSTATUSCHECKANDUPDATE = "CLAW.CUSTOMER.MANAGECUSTOMERS.MYLOADSSTATUSCHECKANDUPDATE";
        //CARRIER
        public const string CARRIER_SEARCHANDOPEN = "CLAW.CARRIER.SEARCHANDOPEN";
        public const string CARRIER_VERIFYDETAILS = "CLAW.CARRIER.VERIFYDETAILS";
        public const string CARRIER_APPACCESS = "CLAW.CARRIER.APPACCESS";
        //AVILLOAD
        public const string AVILOAD_OPEN = "CLAW.AVILLOAD.OPEN";
        public const string AVILLOAD_ADDTRUCK = "CLAW.AVILLOAD.ADDTRUCK";
        public const string AVILLOAD_MAKEOFFEROPEN = "CLAW.AVILLOAD.MAKEOFFEROPEN";
        public const string AVILLOAD_ClOSE = "CLAW.AVILLOAD.ClOSE";
        public const string AVILLOAD_ADVFILTER = "CLAW.AVILLOAD.ADVFILTER";
        public const string AVILLOAD_SEARCHRESULT = "CLAW.AVILLOAD.SEARCHRESULT";
        public const string AVILLOAD_MATCHTRUCKS = "CLAW.AVILLOAD.MATCHTRUCKS";
        public const string AVILLOAD_REMOVETRUCK = "CLAW.AVILLOAD.REMOVETRUCK";
        public const string AVILLOAD_GETAVILABLELOADDETAILS = "CLAW.AVILLOAD.GETAVILABLELOADDETAILS";
        //CREATELOAD
        public const string CREATELOAD_FILL = "CLAW.CREATELOAD.FILL";
        public const string CREATELOAD_SUBMIT = "CLAW.CREATELOAD.SUBMIT";
        //MYLOAD
        public const string MYLOAD_SEARCH = "CLAW.MYLOAD.SEARCH";
        public const string MYLOAD_VALIDATERESULT = "CLAW.MYLOAD.VALIDATERESULT";
        public const string MYLOAD_ADVANCEDSEARCH = "CLAW.MYLOAD.ADVSEARCH";
        public const string MYLOAD_SEARCHANDOPENLOAD = "CLAW.MYLOAD.SEARCHANDOPENLOAD";
        public const string MYLOAD_TOGGLECOL_SELECT = "CLAW.MYLOAD.TOGGLECOL.SELECT";
        public const string MYLOAD_TOGGLECOL_VERIFY = "CLAW.MYLOAD.TOGGLECOL.VERIFY";
        public const string MYLOAD_GETLOADDETAILS = "CLAW.MYLOAD.GETDETAILS";
        public const string MYLOAD_ADVSEARCH_DISPACHED = "CLAW.MYLOAD.ADVSEARCH.DISPACHED";
        public const string MYLOAD_PICKUP_STOP_EDIT = "CLAW.MYLOAD.PICKUP.STOP.EDIT";
        public const string MYLOAD_DELIVERY_STOP_EDIT = "CLAW.MYLOAD.DELIVERY.STOP.EDIT";
        public const string MYLOAD_TRACKING_GENINFO_VERFIY = "CLAW.MYLOAD.TRACKING.GENINFO.VERFIY";
        public const string MYLOAD_COMMODITIES_EDIT = "CLAW.MYLAOD.COMMODITIES.EDIT";
        public const string MYLOAD_DOCUMENTS_UPLOAD = "CLAW.MYLAOD.DOCUMENTS.UPLOAD";
        public const string MYLOAD_DISPLAYED_COL_VERIFICATION = "CLAW.MYLAOD.DISPLAYED.COL.VERIFICATION";
        //LOAD
        public const string LOAD_VERFIYDETAILS = "CLAW.LOAD.VERFIY";
        public const string LOAD_INQUIRE = "CLAW.LOAD.INQUIRE";
        public const string LOAD_VERIFY_BOL_EDIT_STATUS = "CLAW.LAOD.VERIFYBOLEDITSTATUS";
        public const string LOAD_VERIFY_POD_EDIT_STATUS = "CLAW.LAOD.VERIFYPODEDITSTATUS";
        public const string LOAD_VERIFY_CHARGES = "CLAW.LAOD.VERIFYCHARGES";
        //FACILITY CALENDAR
        public const string FACILITYCALENDAR_NAVIGATION = "CLAW.FACILITYCALENDAR.NAVIGATION";
        public const string FACILITYCALENDAR_DROPDOWN = "CLAW.FACILITYCALENDAR_DROPDOWN";
        public const string FACILITYCALENDAR_CREATEEVENT = "CLAW.FACILITYCALENDAR.CREATEEVENT";
        public const string FACILITYCALENDAR_EXPORT = "CLAW.FACILITYCALENDAR_EXPORT";
        public const string FACILITYCALENDAR_OPENEVENT = "CLAW.FACILITYCALENDAR.OPENEVENT";
        public const string FACILITYCALENDAR_GETLOADDETAILS = "CLAW.FACILITYCALENDAR.GETLOADDETAILS";
        public const string FACILITYCALENDAR_OPENLOAD = "CLAW.FACILITYCALENDAR.OPENLOAD";
        //CUSTOMER REPORTING
        public const string CUSTOMERREPORTING_NAVIGATION = "CLAW.CUSTOMERREPORTING.NAVIGATION";
        public const string CUSTOMERREPORTING_GENRALINFO_VERIFY = "CLAW.CUSTOMERREPORTING.GENRALINFO.VERIFY";
        public const string CUSTOMERREPORTING_PREMIUM_REPORT = "CLAW.CUSTOMERREPORTING.PREMIUM.REPORT";
        //CREATE ORDER
        public const string CREATEORDER_FILL = "CLAW.CREATEORDER.FILL";
        public const string CREATEORDER_NAVIGATE = "CLAW.CREATEORDER.NAVIGATE";
        public const string CREATEORDER_CANCEL = "CLAW.CREATEORDER.CANCEL";
        public const string CREATEORDER_SAVE = "CLAW.CREATEORDER.SAVE";
        public const string CREATEORDER_SHIPORDER = "CLAW.CREATEORDER.SHIPORDER";
        public const string CREATEORDER_SHIPPINGUINT_ADD = "CLAW.CREATEORDER.SHIPPINGUINT.ADD";
        public const string CREATEORDER_SHIPPINGUINT_FILL = "CLAW.CREATEORDER.SHIPPINGUINT.FILL";
        public const string CREATEORDER_SHIPPINGUINT_ADDANDFILL = "CLAW.CREATEORDER.SHIPPINGUINT.ADDANDFILL";
        public const string CREATEORDER_COMMODITY_ADD = "CLAW.CREATEORDER.COMMODITY.ADD";
        public const string CREATEORDER_COMMODITY_FILL = "CLAW.CREATEORDER.COMMODITY.FILL";
        public const string CREATEORDER_COMMODITY_SELECT_ALL = "CLAW.CREATEORDER.COMMODITY.SELECTALL";
        public const string CREATEORDER_COMMODITY_SELECT_NONE = "CLAW.CREATEORDER.COMMODITY.SELECTNONE";
        public const string CREATEORDER_COMMODITY_SELECT_MOVE = "CLAW.CREATEORDER.COMMODITY.SELECTMOVE";
        public const string CREATEORDER_COMMODITY_SELECT_DELETE = "CLAW.CREATEORDER.COMMODITY.SELECTDELETE";

    }
}